Repository kustaurant/Android, pull requests merged in 2025-02, with the labels that each got.

#108 [Bug#111] 음식 카테고리 선택 시, 아이템 테두리 잘림 현상 / [Design#107] 뽑기 결과 애니메이션 UI를 웹, IOS와 통일
  .idea/deploymentTargetSelector.xml
  .idea/runConfigurations.xml
  app/src/main/java/com/kust/kustaurant/presentation/common/BindingAdapters.kt
  app/src/main/java/com/kust/kustaurant/presentation/common/CategoryData.kt
  app/src/main/java/com/kust/kustaurant/presentation/common/CategoryIdMapper.kt
  app/src/main/java/com/kust/kustaurant/presentation/common/DimensionUtils.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityBlankFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostDetailFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostDetailViewModel.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostListAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostListFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostRankingFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityViewModel.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/draw/DrawCategoryAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/draw/DrawResultFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/draw/DrawSelectCategoryFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/draw/DrawSelectResultAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/draw/DrawViewModel.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/home/CategoryAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/home/HomeFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierViewModel.kt
  app/src/main/res/drawable/all_radius_30_signature_1.xml
  app/src/main/res/drawable/btn_selector_draw_category.xml
  app/src/main/res/layout/fragment_community_blank.xml
  app/src/main/res/layout/fragment_draw_result.xml
  app/src/main/res/layout/fragment_draw_select_category.xml
  app/src/main/res/layout/item_draw_select_result_img.xml
  app/src/main/res/values/dimens.xml
Labels: bug, feat, 조정범

#113 [Bug#112] 배너 indicator 오류 해결
  app/src/main/java/com/kust/kustaurant/presentation/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: bug, 송민서

#120 [Feat] base url 숨기는 작업
  app/build.gradle.kts
  app/src/main/java/com/kust/kustaurant/data/network/TokenAuthenticator.kt
  app/src/main/java/com/kust/kustaurant/di/network/NetworkModule.kt
Labels: feat, 송민서

#122 [Refactor/#110] mypage 및 데이터 형식 수정
  .idea/.name
  app/src/main/java/com/kust/kustaurant/data/model/MyCommunityListResponse.kt
  app/src/main/java/com/kust/kustaurant/data/model/MyPageResponse.kt
  app/src/main/java/com/kust/kustaurant/data/model/MyScrapResponse.kt
  app/src/main/java/com/kust/kustaurant/data/network/TokenAuthenticator.kt
  app/src/main/java/com/kust/kustaurant/presentation/common/CommunityRegex.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostListAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/MyCommentActivity.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/MyEvaluateActivity.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/MyPostActivity.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/MySaveActivity.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/MyScrapActivity.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/PostAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/mypage/ScrapAdapter.kt
  app/src/main/res/layout/activity_my_comment.xml
  app/src/main/res/layout/activity_my_evaluate.xml
  app/src/main/res/layout/activity_my_post.xml
  app/src/main/res/layout/activity_my_save.xml
  app/src/main/res/layout/activity_my_scrap.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_my_post.xml
  app/src/main/res/layout/item_my_scrap.xml
Labels: refactoring, 김태정

#123 [Fix & Feat] 티어탭 관련 버그 및 커뮤니티 게시글 관련 버그 수정, 평가하기와 즐겨찾기를 위한 백엔드 로직 추가
  app/build.gradle.kts
  app/src/main/assets/quill.html
  app/src/main/java/com/kust/kustaurant/data/mapper/TierMapDataMapper.kt
  app/src/main/java/com/kust/kustaurant/data/model/TierMapData.kt
  app/src/main/java/com/kust/kustaurant/data/model/TierMapDataResponse.kt
  app/src/main/java/com/kust/kustaurant/data/remote/TierApi.kt
  app/src/main/java/com/kust/kustaurant/data/repository/TierRepositoryImpl.kt
  app/src/main/java/com/kust/kustaurant/domain/repository/TierRepository.kt
  app/src/main/java/com/kust/kustaurant/domain/usecase/tier/GetAuthTierListDataUseCase.kt
  app/src/main/java/com/kust/kustaurant/domain/usecase/tier/GetAuthTierRestaurantMapUseCase.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/community/CommunityPostWriteViewModel.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierListAdapter.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierListFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierMapFragment.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierScreenType.kt
  app/src/main/java/com/kust/kustaurant/presentation/ui/tier/TierViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_tier_category_select.xml
  app/src/main/res/layout/fragment_tier_map.xml
  app/src/main/res/layout/item_restaurant_expand.xml
  app/src/main/res/layout/item_restaurant_reduction.xml
  app/src/main/res/layout/item_search_restaurant.xml
  app/src/main/res/layout/layout_restaurant_bottom_sheet.xml
Labels: bug, feat, 조정범
